import { describe, expect, it } from 'vitest';
import { buildTaskChain } from '../src/services/taskChainBuilder';
import type { CalendarEntryType } from '../src/types/domain/calendarEntry';

const CONTENT_ID = '11111111-1111-1111-1111-111111111111';
const PRODUCTION_ID = '22222222-2222-2222-2222-222222222222';

const ASSIGNEES = {
  content_engagement: CONTENT_ID,
  digital_marketing_production: PRODUCTION_ID,
} as const;

const ENTRY_DATE = '2026-04-10';

describe('buildTaskChain', () => {
  it.each(['tiktok_video', 'ig_video', 'snap_spotlight'] as const)(
    '%s: emits 4 tasks with staggered dates and role-aware assignees',
    (type: CalendarEntryType) => {
      const chain = buildTaskChain({
        entryType: type,
        entryDate: ENTRY_DATE,
        assigneesByRole: ASSIGNEES,
      });

      expect(chain).toEqual([
        { step: 'script', dueDate: '2026-04-07', assigneeId: CONTENT_ID },
        { step: 'shoot', dueDate: '2026-04-08', assigneeId: PRODUCTION_ID },
        { step: 'edit', dueDate: '2026-04-09', assigneeId: PRODUCTION_ID },
        { step: 'post', dueDate: '2026-04-10', assigneeId: PRODUCTION_ID },
      ]);
    },
  );

  it.each(['snap_story', 'ig_story'] as const)(
    '%s: emits a single post task on the entry date assigned to content_engagement',
    (type: CalendarEntryType) => {
      const chain = buildTaskChain({
        entryType: type,
        entryDate: ENTRY_DATE,
        assigneesByRole: ASSIGNEES,
      });
      expect(chain).toEqual([{ step: 'post', dueDate: ENTRY_DATE, assigneeId: CONTENT_ID }]);
    },
  );

  it('shoot entry: emits a single shoot task on the entry date to production', () => {
    const chain = buildTaskChain({
      entryType: 'shoot',
      entryDate: ENTRY_DATE,
      assigneesByRole: ASSIGNEES,
    });
    expect(chain).toEqual([{ step: 'shoot', dueDate: ENTRY_DATE, assigneeId: PRODUCTION_ID }]);
  });

  it.each(['shop_activity', 'offer'] as const)(
    '%s: emits no tasks (generated by their own modules)',
    (type: CalendarEntryType) => {
      const chain = buildTaskChain({
        entryType: type,
        entryDate: ENTRY_DATE,
        assigneesByRole: ASSIGNEES,
      });
      expect(chain).toEqual([]);
    },
  );

  it('returns an empty chain when shoot_weekly_post_daily is set (Chunk 6 path)', () => {
    const chain = buildTaskChain({
      entryType: 'snap_story',
      entryDate: ENTRY_DATE,
      assigneesByRole: ASSIGNEES,
      shootWeeklyPostDaily: true,
    });
    expect(chain).toEqual([]);
  });

  it('handles month boundaries (offset spanning into previous month)', () => {
    const chain = buildTaskChain({
      entryType: 'tiktok_video',
      entryDate: '2026-04-01',
      assigneesByRole: ASSIGNEES,
    });
    expect(chain[0]?.dueDate).toBe('2026-03-29');
    expect(chain[3]?.dueDate).toBe('2026-04-01');
  });
});
